### ISSUE TITLE
Add prayer button in "Pray For Remember Thee" section

### ISSUE THREAD

**Issue by tdowds** [tdowds/rememberthee-website#19]
To gauge demand for Remember Thee, an interesting indicator to explore would be how many people are praying for the app.

To measure we should do the following:

- [ ] In the "Pray For Remember Thee" section, add a prayer emoji below the paragraph
- [ ] Make the prayer emoji a button
- [ ] Upon pressing the prayer emoji button, make a `POST` request to the backend at `/pray`
- [ ] Provide some visual indicator to the user that the prayer emoji button has been pressed
- [ ] On the backend create a route for `POST /pray` and have it always return `200`

**Comment by michaelyaacoub** [comment]
**### When it comes to the button, would be something like this?**

![Screen Shot 2021-11-06 at 1 07 47 AM](https://user-images.githubusercontent.com/56051759/140602833-4f5bba35-b7c8-4c0c-8959-76cf63d5c298.png)

**Comment by tdowds** [comment]
I'd say make the emoji the button itself - no black background and only one emoji (and perhaps slightly bigger). Do need some kind of animation or indicator that the button has been pressed

**Comment by michaelyaacoub** [comment]
Got you! Let me think and come up with something for it.

**Comment by michaelyaacoub** [comment]
Also thinking if the emoji does not still grab people's attention, we could add a CSS keyframe to make it shake or have an animated circle around it, lmk if this is too much!

**Comment by tdowds** [comment]
closed via #25
